server:
  port: 9080

spring:
  application:
    name: OtpService
  jmx:
    default-domain: OtpService
    unique-names: true
  jpa: 
    show-sql: true
# 多國語系設定檔(多檔請以 "," 區隔 e.g: i18n/message)
  messages:
    basename: i18n/message